### ISSUE TITLE
tags not working? 

### ISSUE THREAD

**Issue by akamkomputer** [guillaumebriday/lobsters-docker#1]
is it possible, that the tags are not working in this build? 
maybe related to: https://github.com/lobsters/lobsters/issues/633

:-) AK

**Comment by guillaumebriday** [comment]
Hey ! You're right

I'm reverting again with the official repo to trig a new build as soon as possible.

It's a pain in the a** to know when to build a new image because they don't want to follow semver as I mentioned here : https://github.com/lobsters/lobsters/issues/618

Sorry for the inconvenience

**Comment by guillaumebriday** [comment]
I updated my containers in production this morning and it works fine 👍
